--OZEL HESAP KAPATMALI BEKLEYEN CARI HAREKETLER

WITH TMP AS (SELECT A.SUBE_KODU,CARI_KOD,TARIH,VADE_TARIHI,BELGE_NO,HAREKET_TURU HT,ACIKLAMA,ROW_NUMBER() OVER(PARTITION BY CARI_KOD ORDER BY CARI_KOD,VADE_TARIHI,INC_KEY_NUMBER) SIRA,
DOVIZ_TURU DT, (SELECT CAST(CM_BORCT - CM_ALACT AS money) FROM TBLCASABIT U WHERE U.CARI_KOD=A.CARI_KOD) BAKIYE,
BORC,CASE WHEN BORC>0 THEN BORC - ROUND((CASE WHEN ROUND(DOVIZ_TUTAR,2)>0 AND DOVIZ_TURU<>0 THEN (BORC+ALACAK)/ROUND(DOVIZ_TUTAR,2) ELSE 1 END)*KAPATILMIS_TUTAR,2) ELSE 0 END GBORC,
ALACAK, CASE WHEN ALACAK>0 THEN ALACAK - ROUND((CASE WHEN ROUND(DOVIZ_TUTAR,2)>0 AND DOVIZ_TURU<>0 THEN (BORC+ALACAK)/ROUND(DOVIZ_TUTAR,2) ELSE 1 END)*KAPATILMIS_TUTAR,2) ELSE 0 END GALACAK,
--KAPATILMIS_TUTAR,DOVIZ_TUTAR,
--ROUND((CASE WHEN ROUND(DOVIZ_TUTAR,2)>0 AND DOVIZ_TURU<>0 THEN (BORC+ALACAK)/ROUND(DOVIZ_TUTAR,2) ELSE 1 END)*KAPATILMIS_TUTAR,2) KAPTL_TUTAR,
DATEDIFF(d,GETDATE(),VADE_TARIHI) GUN,A.INC_KEY_NUMBER,
ROUND((DATEDIFF(d,GETDATE(),VADE_TARIHI))*((CASE WHEN BORC>0 THEN BORC - ROUND((CASE WHEN ROUND(DOVIZ_TUTAR,2)>0 AND DOVIZ_TURU<>0 THEN (BORC+ALACAK)/ROUND(DOVIZ_TUTAR,2) ELSE 1 END)*KAPATILMIS_TUTAR,2) ELSE 0 END) - (CASE WHEN ALACAK>0 THEN ALACAK - ROUND((CASE WHEN ROUND(DOVIZ_TUTAR,2)>0 AND DOVIZ_TURU<>0 THEN (BORC+ALACAK)/ROUND(DOVIZ_TUTAR,2) ELSE 1 END)*KAPATILMIS_TUTAR,2) ELSE 0 END)),2) AS ADAT
--CASE WHEN ACIKLAMA<>'KUR FARKI' THEN DATEDIFF(D,VADE_TARIHI,CAST(GETDATE() AS DATE)) ELSE 0 END GUN
FROM TBLCAHAR A (NOLOCK)
WHERE CARI_KOD IN (SELECT CARI_KOD FROM TBLCASABIT WHERE HESAPTUTMASEKLI='K') AND 
BORC + ALACAK > ROUND((CASE WHEN ROUND(DOVIZ_TUTAR,2)>0 AND DOVIZ_TURU<>0 THEN (BORC+ALACAK)/ROUND(DOVIZ_TUTAR,2) ELSE 1 END)*KAPATILMIS_TUTAR,2)
--ORDER BY CARI_KOD,TARIH,SIRA
)
SELECT * --,ROUND(ADAT/(GBORC + GALACAK),0) ORT
FROM TMP
WHERE GBORC + GALACAK=0